### ISSUE TITLE
How do I create a highload wallet? I can't find the option to create a highload wallet in Tonkeeper web. I need to be able to send multiple transfers at once. Can I use W5 wallet instead of highload wallet to do this?

### ISSUE THREAD

**Issue by ks-39** [neodix42/ton4j#75]

**Comment by Henrywilliam96** [comment]
Hey @ks-39  

To create a highload wallet in Tonkeeper, you typically need to look for options related to wallet settings or advanced features. If you can't find the option, it might not be available in the web version yet or could be located in a different section.

Regarding using the W5 wallet instead of a highload wallet for multiple transfers, it depends on the capabilities of the W5 wallet. If it supports batch transactions or multiple transfers, then you should be able to use it for that purpose. Check the documentation or support resources for the W5 wallet to confirm its features.

If you need further assistance, feel free to ask!

**Comment by neodix42** [comment]
Please look at this example on how to use wallet v5 with ton4j https://github.com/neodix42/ton4j/blob/main/smartcontract/src/test/java/org/ton/java/smartcontract/integrationtests/TestWalletV5.java
Please ask the Tonkeeper team about highload questions. It might be that there is no way to create highload wallet from its UI.

**Comment by ks-39** [comment]
> Please look at this example on how to use wallet v5 with ton4j https://github.com/neodix42/ton4j/blob/main/smartcontract/src/test/java/org/ton/java/smartcontract/integrationtests/TestWalletV5.java Please ask the Tonkeeper team about highload questions. It might be that there is no way to create highload wallet from its UI.

Ok, thanks for your reply!
